In [4]:
import pandas as pd

## Оцінка параметрів

In [5]:
df = pd.read_csv('dkr6_data.csv')
df

  Альтернатива  Вартість  Розмір  Стан  Відстань
0           A1         0       1     2         2
1           A2         0       1     2         1
2           A3         0       2     1         1
3           A4         0       1     2         0
4           A5         1       0     0         2
5           A6         0       1     0         1
6           A7         0       0     2         1
7           A8         1       1     0         0
8           A9         0       0     1         0
9          A10         1       2     2         0

* Варітсть: 0 -дорого, 1 -недорого
* Розмір: 0 -малий, 1 - середній, 2 - великий
* Стан: 0 - капітальний ремонт, 1 - потребує косметичний ремонт, 2 - проведено капітальний ремонт
* Відстань: 0 - поза містом, 1 - далеко від центру, 2 - недалеко

In [6]:
criteria = ["Вартість", "Розмір", "Стан", "Відстань"]
data = df[criteria].values

def dominates(a, b):
    return all(a_i >= b_i for a_i, b_i in zip(a, b)) and any(a_i > b_i for a_i, b_i in zip(a, b))

pareto = []
for i, row_i in enumerate(data):
    if not any(dominates(other, row_i) for j, other in enumerate(data) if j != i):
        pareto.append(i)

pareto_df = df.iloc[pareto]
print("Множина Еджворта-Парето:")
pareto_df

Множина Еджворта-Парето:

  Альтернатива  Вартість  Розмір  Стан  Відстань
0           A1         0       1     2         2
2           A3         0       2     1         1
4           A5         1       0     0         2
9          A10         1       2     2         0